names:
- Hardhat
- Mask
- NO-Hardhat
- NO-Mask
- NO-Safety Vest
- Person
- Safety Cone
- Safety Vest
- machinery
- vehicle
nc: 10
test: /content/YOLO_Project/css-data/test
train: /content/YOLO_Project/css-data/train
val: /content/YOLO_Project/css-data/valid
